import Head from 'next/head';
import Image from 'next/image';
import { Counter } from '@/components/Counter';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>
            Get started by editing&nbsp;
            <code>src/pages/index.tsx</code>
          </p>
          <Counter />
        </div>
      </main>
    </>
  );
}
